### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by zoranmarjanovic** [rmlevangelio/fcg-cars#1]
Hey @rmlevangelio, I'm just wondering about progress - can't find if it is ready for review or you want to change some more stuffs

**Comment by rmlevangelio** [comment]
Hi @zoranmarjanovic I still have something in my mind to implement for the task. I will be done by tomorrow.

**Comment by rmlevangelio** [comment]
@zoranmarjanovic I just pushed my latest update. It's now ready for review. Please let me know your thoughts ;) Thank you a lot

**Comment by rmlevangelio** [comment]
Hi @zoranmarjanovic, did you get the chance to review my exam? Thanks.

**Comment by zoranmarjanovic** [comment]
Yup, I'll check it today, thanks!

**Comment by rmlevangelio** [comment]
Hi @zoranmarjanovic , any feedback about my exam? :) I’m just curious if you have any questions about it and looking forward to talk to you sometime :)
